spring.application.name=crud-pessoa

#H2 Database
spring.datasource.url=jdbc:h2:mem:AR_crud_pessoa/$createDatabaseIfNotExist=true
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

#MYSQL
#spring.datasource.url=jdbc:mysql://localhost/${MYSQL_DATABSE}/$createDatabaseIfNotExist=true
#spring.datasource.username=${MYSQL_USERNAME:}
#spring.datasource.password=${MYSQL_PASSWORD:}
